# Generated by Django 5.2.11 on 2026-03-08 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('fleets', '0001_initial'),
        ('jobs', '0001_initial'),
        ('safety_forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_managers',
            field=models.ManyToManyField(blank=True, help_text='One or more managers overseeing this job', limit_choices_to={'is_staff': True, 'is_superuser': False}, related_name='managed_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Single employee (plumber) assigned to this job', limit_choices_to={'is_staff': False, 'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='clients.client'),
        ),
        migrations.AddField(
            model_name='job',
            name='safety_forms',
            field=models.ManyToManyField(blank=True, help_text='Safety form templates required for this job', related_name='jobs', to='safety_forms.safetyformtemplate'),
        ),
        migrations.AddField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehicle assigned to this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='fleets.vehicle'),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobattachment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joblineitem',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobnote',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobnote',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobphoto',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobphoto',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.job'),
        ),
    ]
