# Generated by Django 5.2.11 on 2026-03-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=500),
        ),
    ]
