# Generated by Django 5.2.11 on 2026-03-08 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Display label shown to the employee e.g. 'Vehicle Condition'", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('date', 'Date'), ('time', 'Time'), ('file', 'File Upload')], default='text', max_length=20)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for select/multi-select fields e.g. Good,Fair,Poor')),
                ('is_required', models.BooleanField(default=False, help_text='If true, employee must fill this field before submitting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order. Lower number appears first.')),
                ('helper_text', models.CharField(blank=True, help_text='Optional hint shown below the field in the form.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Safety Form Field',
                'verbose_name_plural': 'Safety Form Fields',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyFormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Safety Form Submission',
                'verbose_name_plural': 'Safety Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive forms will not appear to employees or be selectable for jobs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Safety Form Template',
                'verbose_name_plural': 'Safety Form Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SafetyFormResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='safety_forms/uploads/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='safety_forms.safetyformfield')),
            ],
            options={
                'verbose_name': 'Safety Form Response',
                'verbose_name_plural': 'Safety Form Responses',
            },
        ),
    ]
