# Generated by Django 5.2.11 on 2026-03-08 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        ('safety_forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyformsubmission',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_form_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safetyformsubmission',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_form_submissions', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='safetyformresponse',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='safety_forms.safetyformsubmission'),
        ),
        migrations.AddField(
            model_name='safetyformsubmission',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='safety_forms.safetyformtemplate'),
        ),
        migrations.AddField(
            model_name='safetyformfield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='safety_forms.safetyformtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='safetyformresponse',
            unique_together={('submission', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='safetyformsubmission',
            unique_together={('job', 'template', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='safetyformfield',
            unique_together={('template', 'order')},
        ),
    ]
