# Generated by Django 5.2.11 on 2026-03-08 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionCheckItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('lights', 'Lights'), ('tires', 'Tires'), ('brakes', 'Brakes'), ('fluid_levels', 'Fluid Levels'), ('mirrors', 'Mirrors'), ('horn', 'Horn'), ('windshield_wipers', 'Windshield & Wipers'), ('dashboard_warning_lights', 'Dashboard Warning Lights'), ('body_exterior', 'Body Exterior')], max_length=30)),
                ('is_ok', models.BooleanField(default=True)),
                ('issue_detail', models.TextField(blank=True, help_text='Required when is_ok=False.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_open_issue', models.BooleanField(default=False, help_text='True if any check item has is_ok=False.')),
                ('notes', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Inspection',
                'verbose_name_plural': 'Vehicle Inspections',
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionCheckPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='fleet_inspections/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('check_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fleet_inspections.inspectioncheckitem')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
