# Generated by Django 5.2.11 on 2026-03-08 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet_inspections', '0001_initial'),
        ('fleets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='inspected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='fleets.vehicle'),
        ),
        migrations.AddField(
            model_name='inspectioncheckitem',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='fleet_inspections.vehicleinspection'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectioncheckitem',
            unique_together={('inspection', 'category')},
        ),
    ]
