# Generated by Django 5.2.11 on 2026-03-08 19:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Client company or individual name', max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='clients/pictures/')),
                ('address', models.CharField(help_text='Full address — rendered as Google Maps hyperlink in app and dashboard', max_length=500)),
                ('contact_person_name', models.CharField(blank=True, help_text='Name of the on-site contact person', max_length=150)),
                ('site_access', models.TextField(blank=True, help_text='e.g. Gate B, Code 4589 — access instructions for staff')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
    ]
