# Generated by Django 5.2.11 on 2026-03-08 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Van 04, Ute 02', max_length=150)),
                ('plate', models.CharField(help_text='Vehicle number plate e.g. ABC-1234', max_length=20, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='fleet/vehicles/')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('issue_reported', 'Issue Reported'), ('inspection_due', 'Inspection Due'), ('service_overdue', 'Service Overdue')], default='healthy', max_length=20)),
                ('current_odometer_km', models.PositiveIntegerField(blank=True, help_text='Current odometer reading in km', null=True)),
                ('next_service_km', models.PositiveIntegerField(blank=True, help_text='Odometer reading (km) at which next service is due', null=True)),
                ('make', models.CharField(blank=True, help_text='e.g. Toyota', max_length=100)),
                ('model_name', models.CharField(blank=True, help_text='e.g. HiAce', max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('description', models.TextField(help_text='What maintenance is being performed')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('odometer_at_service', models.PositiveIntegerField(blank=True, help_text='Odometer reading when service was performed', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('performed_by', models.CharField(blank=True, help_text='Service center or mechanic name', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='fleets.vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance Schedule',
                'verbose_name_plural': 'Maintenance Schedules',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
