# Generated by Django 5.2.11 on 2026-03-08 19:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FCM Token',
                'verbose_name_plural': 'FCM Tokens',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('welcome', 'Welcome'), ('pass_updated', 'Password Updated'), ('pass_changed', 'Password Changed'), ('vehicle_registered', 'Vehicle Registered'), ('maintenance_added', 'Maintenance Added'), ('maintenance_completed', 'Maintenance Completed'), ('maintenance_due', 'Maintenance Due'), ('diagnostic_saved', 'Diagnostic Report Saved'), ('subs_purchased', 'Subscription Purchased'), ('subs_expiring', 'Subscription Expiring'), ('subs_expired', 'Subscription Expired'), ('app_update', 'App Update Available'), ('new_user', 'New User Joined'), ('milestone_achieved', 'Milestone Achieved'), ('support_request', 'Support Request')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('sent_via_fcm', models.BooleanField(default=False)),
                ('sent_via_websocket', models.BooleanField(default=False)),
                ('fcm_success', models.BooleanField(default=False)),
                ('websocket_success', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
