# Generated by Django 5.2.11 on 2026-03-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='fcm_success',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_via_fcm',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_via_websocket',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='websocket_success',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('pass_updated', 'Password Updated'), ('pass_changed', 'Password Changed'), ('job_assigned', 'Job Assigned'), ('job_updated', 'Job Updated'), ('job_started', 'Job Started'), ('job_completed', 'Job Completed'), ('job_overdue', 'Job Overdue'), ('job_rescheduled', 'Job Rescheduled'), ('safety_form_submitted', 'Safety Form Submitted'), ('vehicle_issue_reported', 'Vehicle Issue Reported'), ('vehicle_inspection_due', 'Vehicle Inspection Due'), ('vehicle_service_overdue', 'Vehicle Service Overdue'), ('support_request', 'Support Request'), ('issue_report', 'Issue Report'), ('new_user', 'New User Joined')], max_length=50),
        ),
        migrations.DeleteModel(
            name='FCMToken',
        ),
    ]
